IdentitiyEntity/Models/ProductDetail.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentitiyEntity.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class ProductDetail
    {
        public int id { get; set; }
        public string productname { get; set; }
        public string productimg { get; set; }
        public Nullable<decimal> productprice { get; set; }
        public string userip { get; set; }
        public HttpPostedFileBase file { get; set; }
    }
}

IdentitiyEntity/Controllers/ProductDetailsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IdentitiyEntity.Models;
using System.IO;
using Microsoft.AspNet.Identity.Owin;

namespace IdentitiyEntity.Controllers
{
    public class ProductDetailsController : Controller
    {
        private Entities db = new Entities();

        // GET: ProductDetails
        [Authorize]
        public ActionResult Index()
        {
            return View(db.ProductDetails.ToList());
        }
        [Authorize]
        // GET: ProductDetails/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductDetail productDetail = db.ProductDetails.Find(id);
            if (productDetail == null)
            {
                return HttpNotFound();
            }
            return View(productDetail);
        }
        [Authorize]
        // GET: ProductDetails/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductDetails/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,productname,productimg,productprice,userip,file")] ProductDetail productDetail)
        {
            if (ModelState.IsValid)
            {
                //Use Namespace called :  System.IO  
                string FileName = Path.GetFileNameWithoutExtension(productDetail.file.FileName);

                //To Get File Extension  
                string FileExtension = Path.GetExtension(productDetail.file.FileName);

                //Add Current Date To Attached File Name  
                FileName = DateTime.Now.ToString("yyyyMMdd") + "-" + FileName.Trim() + FileExtension;

                //Its Create complete path to store in server.  
                productDetail.productimg = FileName;

                //To copy and save file into server.  
                productDetail.file.SaveAs(Server.MapPath("~" + ConfigurationManager.AppSettings["UserImagePath"].ToString()) + FileName);
                productDetail.userip = Request.ServerVariables["REMOTE_ADDR"];
                db.ProductDetails.Add(productDetail);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(productDetail);
        }

        // GET: ProductDetails/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductDetail productDetail = db.ProductDetails.Find(id);
            if (productDetail == null)
            {
                return HttpNotFound();
            }
            return View(productDetail);
        }

        // POST: ProductDetails/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,productname,productimg,productprice,file")] ProductDetail productDetail)
        {
            productDetail.userip = Request.ServerVariables["REMOTE_ADDR"];

            //Use Namespace called :  System.IO  
            string FileName = Path.GetFileNameWithoutExtension(productDetail.file.FileName);

            //To Get File Extension  
            string FileExtension = Path.GetExtension(productDetail.file.FileName);

            //Add Current Date To Attached File Name  
            FileName = DateTime.Now.ToString("yyyyMMdd") + "-" + FileName.Trim() + FileExtension;

            //Its Create complete path to store in server.  
            productDetail.productimg = FileName;

            //To copy and save file into server.  
            productDetail.file.SaveAs(Server.MapPath("~" + ConfigurationManager.AppSettings["UserImagePath"].ToString()) + FileName);

            if (ModelState.IsValid)
            {
                db.Entry(productDetail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(productDetail);
        }

        // GET: ProductDetails/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductDetail productDetail = db.ProductDetails.Find(id);
            if (productDetail == null)
            {
                return HttpNotFound();
            }
            return View(productDetail);
        }

        // POST: ProductDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ProductDetail productDetail = db.ProductDetails.Find(id);
            if (new FileInfo(Server.MapPath("~" + ConfigurationManager.AppSettings["UserImagePath"].ToString()) + productDetail.productimg).Exists)
            {
                new FileInfo(Server.MapPath("~" + ConfigurationManager.AppSettings["UserImagePath"].ToString()) + productDetail.productimg).Delete();
            }
            db.ProductDetails.Remove(productDetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

IdentitiyEntity/Views/ProductDetails/Create.cshtml
@model IdentitiyEntity.Models.ProductDetail

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","ProductDetails",FormMethod.Post,new {enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Online Westfield St Lukes Mall - Product Detail</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.productname, "Product Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.productname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.productname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.productimg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" required name="file" class="form-control"/>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.productprice,"Price ($)", htmlAttributes: new { @class = "control-label col-md-2"}) 
            <div class="col-md-10">
                @Html.EditorFor(model => model.productprice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.productprice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IdentitiyEntity/Views/ProductDetails/Delete.cshtml
@model IdentitiyEntity.Models.ProductDetail

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Online Westfield St Lukes Mall - Product Detail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.LabelFor(model => model.productname, "Product Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.productname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.productimg)
        </dt>

        <dd>
            <img src="@System.Configuration.ConfigurationManager.AppSettings["siteurl"].ToString()@System.Configuration.ConfigurationManager.AppSettings["UserImagePath"].ToString()@Url.Content(Model.productimg)" alt="Image" height="250px" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.productprice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.productprice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.userip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.userip)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

IdentitiyEntity/Views/ProductDetails/Details.cshtml
@model IdentitiyEntity.Models.ProductDetail

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Online Westfield St Lukes Mall - Product Detail</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.LabelFor(model => model.productname, "Product Name")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.productname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.productimg)
        </dt>

        <dd>
            <img src="@System.Configuration.ConfigurationManager.AppSettings["siteurl"].ToString()@System.Configuration.ConfigurationManager.AppSettings["UserImagePath"].ToString()@Url.Content(Model.productimg)" alt="Image"  height="250px"  />
        </dd>

        <dt>
            @Html.LabelFor(model => model.productprice, "Price ($)")
        </dt>

        <dd>
            $ @Html.DisplayFor(model => model.productprice)
        </dd>

       
        

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IdentitiyEntity/Views/ProductDetails/Edit.cshtml
@model IdentitiyEntity.Models.ProductDetail

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "ProductDetails", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Online Westfield St Lukes Mall - Product Detail</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.productname,"Product Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.productname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.productname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.productimg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (Request.QueryString["id"] != null)
                {
                    <br />
                    <img src="@System.Configuration.ConfigurationManager.AppSettings["siteurl"].ToString()@System.Configuration.ConfigurationManager.AppSettings["UserImagePath"].ToString()@Url.Content(Model.productimg)" alt="Image" height="50px" />
                }
                <input type="file" required name="file" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.productprice,"Price ($)", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.productprice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.productprice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IdentitiyEntity/Views/ProductDetails/Index.cshtml
@model IEnumerable<IdentitiyEntity.Models.ProductDetail>

@{
    ViewBag.Title = "Index";
}

<h2>Featured Products</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Product Name
        </th>
        <th>
            Image
        </th>
        <th>
           Price ($)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.productname)
            </td>
            <td>
                @if (item.productimg != null)
                {
                    <img src="@System.Configuration.ConfigurationManager.AppSettings["siteurl"].ToString()@System.Configuration.ConfigurationManager.AppSettings["UserImagePath"].ToString()@Url.Content(item.productimg)" alt="Image" height="50px" />
                }
            </td>
            <td>
                $ @Html.DisplayFor(modelItem => item.productprice)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>